INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Vinicius Torres Pascucci', TRUE, 14000.0, '19471-1', TIMESTAMP WITH TIME ZONE '1993-05-01T08:59:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Leonardo Silveira Darias', TRUE, 12000.0, '22565-3', TIMESTAMP WITH TIME ZONE '1994-05-22T10:59:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('João Andrade Silva', TRUE, 11000.0, '88565-4', TIMESTAMP WITH TIME ZONE '1990-07-01T22:45:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Paulo Silveira', FALSE, 8500.0, '23256-2', TIMESTAMP WITH TIME ZONE '1993-12-01T11:30:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Augusto Souza Lima', FALSE, 7500.0, '12145-7', TIMESTAMP WITH TIME ZONE '1991-02-12T23:44:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Carla Damasceno', FALSE, 5500.0, '14785-4', TIMESTAMP WITH TIME ZONE '1995-05-05T20:30:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Roberto Silveira', TRUE, 10500.0, '15542-2', TIMESTAMP WITH TIME ZONE '1992-12-12T21:30:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Caio Silva Martini', FALSE, 5500.0, '14485-4', TIMESTAMP WITH TIME ZONE '1993-05-11T09:31:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Paulo Alexandre Silva', TRUE, 12000.0, '14785-2', TIMESTAMP WITH TIME ZONE '1991-01-12T12:30:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Paula Moraes da Silva', TRUE, 15000.0, '23256-3', TIMESTAMP WITH TIME ZONE '1990-08-12T10:11:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Luiz Silveira', FALSE, 5500.0, '22125-1', TIMESTAMP WITH TIME ZONE '1991-12-12T21:30:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Junior Silva', TRUE, 12000.0, '11452-6', TIMESTAMP WITH TIME ZONE '1991-05-05T12:55:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Fabio Queiroz', TRUE, 10400.0, '56589-7', TIMESTAMP WITH TIME ZONE '1991-02-10T21:55:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Alberto Silva', TRUE, 8500.0, '23256-2', TIMESTAMP WITH TIME ZONE '1996-01-12T18:30:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Luiza Souza Da Silva', FALSE, 5500.0, '22325-4', TIMESTAMP WITH TIME ZONE '1991-12-012T20:30:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Rafael Francisco', TRUE, 12000.0, '23256-4', TIMESTAMP WITH TIME ZONE '1990-03-03T20:30:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Cintia Souza', FALSE, 4500.0, '23254-5', TIMESTAMP WITH TIME ZONE '1990-12-12T15:30:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Cristina Soares', TRUE, 9500.0, '23256-4', TIMESTAMP WITH TIME ZONE '1989-05-05T20:50:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Silvio Santos', TRUE, 9500.0, '22565-4', TIMESTAMP WITH TIME ZONE '1993-05-05T14:30:00Z')
INSERT INTO tb_account_holder (name, exclusive_plan, ballance, account_number, birth_date) VALUES ('Roberto Moraes da Silva', TRUE, 15000.0, '14785-4', TIMESTAMP WITH TIME ZONE '1991-05-05T20:30:00Z')


INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (1, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (2, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (3, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (4, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (5, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (6, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (7, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (8, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (9, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (10, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (11, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (12, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (13, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (14, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (15, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (16, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (17, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (18, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (19, null)
INSERT INTO tb_extract_account_holder (account_holder_id, description) VALUES (20, null)
